export const countryMapping = {
    // Kode negara yang sudah ada...
    'US': 'United States',
    'GB': 'United Kingdom',
    'FR': 'France',
    'DE': 'Germany',
    'IT': 'Italy',
    'ES': 'Spain',
    'CN': 'China',
    'IN': 'India',
    'JP': 'Japan',
    'KR': 'South Korea',
    'BR': 'Brazil',
    'AU': 'Australia',
    'MX': 'Mexico',
    'CA': 'Canada',
    'RU': 'Russia',
    'NG': 'Nigeria',
    'ZA': 'South Africa',
    'AR': 'Argentina',
    'SE': 'Sweden',
    'NO': 'Norway',
    'DK': 'Denmark',
    'FI': 'Finland',
    'PL': 'Poland',
    'NL': 'Netherlands',
    'BE': 'Belgium',
    'CH': 'Switzerland',
    'AT': 'Austria',
    'SG': 'Singapore',
    'ID': 'Indonesia',
    'TH': 'Thailand',
    'PH': 'Philippines',
    'MY': 'Malaysia',
    'EG': 'Egypt',
    'KW': 'Kuwait',
    'SA': 'Saudi Arabia',
    'AE': 'United Arab Emirates',
    'PE': 'Peru',
    'CO': 'Colombia',
    'CL': 'Chile',
    'VE': 'Venezuela',
    'PK': 'Pakistan',
    'BD': 'Bangladesh',
    'KE': 'Kenya',
    'TZ': 'Tanzania',
    'UG': 'Uganda',
    'RO': 'Romania',
    'HU': 'Hungary',
    'CZ': 'Czech Republic',
    'GR': 'Greece',
    'PT': 'Portugal',
    'TR': 'Turkey',
    'UA': 'Ukraine',
    'HR': 'Croatia',
    'LT': 'Lithuania',
    'LV': 'Latvia',
    'EE': 'Estonia',
    'BG': 'Bulgaria',
    'SK': 'Slovakia',
    'SI': 'Slovenia',
    'IS': 'Iceland',
    'MT': 'Malta',
    'MK': 'North Macedonia',
    'AL': 'Albania',
    'RS': 'Serbia',
    'BA': 'Bosnia and Herzegovina',
    'ME': 'Montenegro',
    'AM': 'Armenia',
    'GE': 'Georgia',
    'AZ': 'Azerbaijan',
    'AE': 'United Arab Emirates',
    'BT': 'Bhutan',
    'BY': 'Belarus',
    'ZW': 'Zimbabwe',
    'MQ': 'Martinique',
    'NC': 'New Caledonia',
    'SC': 'Seychelles',
    'GF': 'French Guiana',
    'GP': 'Guadeloupe',
    'RE': 'Réunion',
    'YT': 'Mayotte',
    'PF': 'French Polynesia',
    'BO': 'Bolivia',
    'DO': 'Dominican Republic',
    'JP': 'Japan',
    'ID': 'Indonesia',
    'KE': 'Kenya',
    'MY': 'Malaysia',
    'PH': 'Philippines',
    'PR': 'Puerto Rico',
    'PE': 'Peru',
    'SG': 'Singapore',
    'CL': 'Chile',
    'QA': 'Qatar',
    'RS': 'Serbia',
    'MA': 'Morocco',
    'MA': 'Morocco',
    'EN': 'English',
    'ZH': 'Mandarin',
    'AF': 'Afrikaans',
    'HI': 'Hindi',
    'CS': 'Czezh',
    'JA': 'Japanese',
    'KO': 'Korean'
};
